# -*- coding: utf-8 -*-
"""StructureAware_NLI_Electra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QDLSKFhXFcVV1vGFYpGgiMbTW-A9oDcy
"""

# imports, installs
!pip install -q transformers datasets scikit-learn


import json
import torch
import random
from sklearn.model_selection import train_test_split
from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
)

nli_model_name = "ynie/electra-large-discriminator-snli_mnli_fever_anli_R1_R2_R3-nli"
tokenizer = AutoTokenizer.from_pretrained(nli_model_name)

# 🧾 Load unmasked Hugging Face dataset
unmasked_raw = load_dataset("MidhunKanadan/logical-fallacy-classification", split="train")

# Format unmasked dataset as NLI pairs
def format_nli(example):
    return {
        "premise": example["statement"],
        "hypothesis": f"This is an example of {example['label']}.",
        "label": example["label"]
    }


unmasked_dataset = unmasked_raw.map(format_nli)

# 🧾 Load masked dataset from local file (masked_output.jsonl)
with open("labeled_masked_output.jsonl", "r") as f:
    masked_data = [json.loads(line) for line in f]


masked_dataset = Dataset.from_list([
    {
        "premise": entry["masked"],
        "hypothesis": f"This is an example of {entry['label']}.",
        "label": entry["label"]
    } for entry in masked_data
])

# 🔁 Label mapping
all_labels = sorted(set(unmasked_dataset["label"]) | set(masked_dataset["label"]))
label2id = {l: i for i, l in enumerate(all_labels)}
id2label = {i: l for l, i in label2id.items()}

# Apply label encoding
def encode_labels(example):
    example["label"] = label2id[example["label"]]
    return example

unmasked_dataset = unmasked_dataset.map(encode_labels)
masked_dataset = masked_dataset.map(encode_labels)

# ✂️ Train/val split
def split_data(dataset):
    return dataset.train_test_split(test_size=0.1, seed=42)["train"], dataset.train_test_split(test_size=0.1, seed=42)["test"]

train_unmasked, val_unmasked = split_data(unmasked_dataset)
train_masked, val_masked = split_data(masked_dataset)

# 🔠 Tokenization
def tokenize(example):
    return tokenizer(example["premise"], example["hypothesis"], truncation=True, padding="max_length", max_length=128)

tokenized_unmasked_train = train_unmasked.map(tokenize, batched=True)
tokenized_unmasked_val = val_unmasked.map(tokenize, batched=True)

tokenized_masked_train = train_masked.map(tokenize, batched=True)
tokenized_masked_val = val_masked.map(tokenize, batched=True)

# Set PyTorch format
for ds in [tokenized_unmasked_train, tokenized_unmasked_val, tokenized_masked_train, tokenized_masked_val]:
    ds.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

# ⚙️ Training args (shared)
def get_training_args(output_dir):
    # Using **kwargs to pass evaluation_strategy for compatibility with older versions
    return TrainingArguments(
        output_dir=output_dir,
        learning_rate=2e-5,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        num_train_epochs=3,
        weight_decay=0.01,
        logging_steps=10,
        save_total_limit=1,
        report_to="none",
        # Pass evaluation_strategy and save_strategy through kwargs
)

# 🔁 Define and train each model
def train_nli_model(train_ds, val_ds, output_dir):
    # Explicitly set num_labels when loading the model
    model = AutoModelForSequenceClassification.from_pretrained(
        nli_model_name,
        num_labels=len(label2id), #  Make sure this matches the number of labels in your dataset
        ignore_mismatched_sizes=True # Ignore mismatched size errors
    )
    trainer = Trainer(
        model=model,
        args=get_training_args(output_dir),
        train_dataset=train_ds,
        eval_dataset=val_ds,
        tokenizer=tokenizer,
    )
    trainer.train()
    trainer.save_model(output_dir)
    tokenizer.save_pretrained(output_dir)
    return trainer

# 🧠 Train both models
trainer_unmasked = train_nli_model(tokenized_unmasked_train, tokenized_unmasked_val, "./nli_unmasked_model")
trainer_masked = train_nli_model(tokenized_masked_train, tokenized_masked_val, "./nli_masked_model")

# 📈 Evaluate both models
print("Evaluating Unmasked Model:")
trainer_unmasked.evaluate()

print("\nEvaluating Masked (Structure-Aware) Model:")
trainer_masked.evaluate()

# print("Evaluating Unmasked Model:")
# trainer_unmasked.evaluate()
from datasets import load_dataset
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# 📘 Load an external test set (e.g., tasksource)
external_test = load_dataset("tasksource/logical-fallacy", split="train")

# 🧹 Clean and format into NLI format
def format_nli(example):
    return {
        "premise": example["source_article"],
        "hypothesis": f"This is an example of {example['logical_fallacies']}.",
        "label": example["logical_fallacies"]
    }

external_test = external_test.map(format_nli)

# 🔁 Filter out labels not in label2id
external_test = external_test.filter(lambda x: x["label"] in label2id)

# 🔢 Encode labels
external_test = external_test.map(lambda x: {"label": label2id[x["label"]]})

# 🔠 Tokenize
external_test = external_test.map(tokenize, batched=True)
external_test.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

# 📊 Helper to get predictions
def get_preds(trainer, test_ds):
    preds = trainer.predict(test_ds)
    y_true = preds.label_ids
    y_pred = np.argmax(preds.predictions, axis=1)
    return y_true, y_pred

# 🧠 Evaluate unmasked model
y_true_unmasked, y_pred_unmasked = get_preds(trainer_unmasked, external_test)
print("📊 Unmasked Model (External Test Set):")
print(f"Accuracy: {accuracy_score(y_true_unmasked, y_pred_unmasked):.4f}")
print(classification_report(y_true_unmasked, y_pred_unmasked, target_names=[id2label[i] for i in sorted(id2label)]))

# 🧠 Evaluate masked model
y_true_masked, y_pred_masked = get_preds(trainer_masked, external_test)
print("\n📊 Masked (Structure-Aware) Model (External Test Set):")
print(f"Accuracy: {accuracy_score(y_true_masked, y_pred_masked):.4f}")
print(classification_report(y_true_masked, y_pred_masked, target_names=[id2label[i] for i in sorted(id2label)]))

# ZERO SHOT
# 🧩 Install required packages
!pip install -q transformers datasets scikit-learn

# 📦 Imports
import json
import torch
import random
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
)

# LOAD DATA
unmasked_raw = load_dataset("MidhunKanadan/logical-fallacy-classification", split="train")

# Format unmasked dataset as NLI pairs
def format_nli(example):
    return {
        "premise": example["statement"],
        "hypothesis": f"This is an example of {example['label']}.",
        "label": example["label"]
    }


unmasked_dataset = unmasked_raw.map(format_nli)

# 🧾 Load masked dataset from local file (masked_output.jsonl)
with open("labeled_masked_output.jsonl", "r") as f:
    masked_data = [json.loads(line) for line in f]


masked_dataset = Dataset.from_list([
    {
        "premise": entry["masked"],
        "hypothesis": f"This is an example of {entry['label']}.",
        "label": entry["label"]
    } for entry in masked_data
])

# 🔁 Label mapping
all_labels = sorted(set(unmasked_dataset["label"]) | set(masked_dataset["label"]))
label2id = {l: i for i, l in enumerate(all_labels)}
id2label = {i: l for l, i in label2id.items()}

# Apply label encoding
def encode_labels(example):
    example["label"] = label2id[example["label"]]
    return example

unmasked_dataset = unmasked_dataset.map(encode_labels)
masked_dataset = masked_dataset.map(encode_labels)

# 🔤 Load tokenizer and model
nli_model_name = "ynie/electra-large-discriminator-snli_mnli_fever_anli_R1_R2_R3-nli"
tokenizer = AutoTokenizer.from_pretrained(nli_model_name)

# 📥 Load UNMASKED dataset
unmasked_raw = load_dataset("MidhunKanadan/logical-fallacy-classification", split="train")

# 🔧 Format unmasked data
def format_nli_unmasked(example):
    return {
        "premise": example["statement"],
        "hypothesis": f"This is an example of {example['label']}.",
        "label": example["label"]
    }

# ✂️ Tokenizer helper
def tokenize(example):
    return tokenizer(example["premise"], example["hypothesis"], truncation=True, padding="max_length", max_length=128)

unmasked_dataset = unmasked_raw.map(format_nli_unmasked)
all_labels = sorted(set(unmasked_dataset["label"]))
label2id = {l: i for i, l in enumerate(all_labels)}
id2label = {i: l for l, i in label2id.items()}

# 🧠 Load pre-trained NLI model (untrained for fallacy classification)
model = AutoModelForSequenceClassification.from_pretrained(
    nli_model_name,
    num_labels=len(label2id),
    ignore_mismatched_sizes=True
)

# 🧪 Load external test set (MASKED version of tasksource)
external_test_unmasked = load_dataset("tasksource/logical-fallacy", split="test")

# 🔧 Format external masked set
def format_nli_masked(example):
    return {
        "premise": example["source_article"],
        "hypothesis": f"This is an example of {example['logical_fallacies']}.",
        "label": example["logical_fallacies"]
    }

external_test_masked = external_test_masked.map(format_nli_masked)

# ✂️ Filter out unknown labels
external_test_unmasked = external_test_masked.filter(lambda x: x["label"] in label2id)
external_test_unmasked = external_test_masked.map(lambda x: {"label": label2id[x["label"]]})
external_test_unmasked = external_test_masked.map(tokenize, batched=True)
external_test_unmasked.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

masked_dataset = masked_dataset.map(tokenize, batched=True)
masked_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

# 📊 Helper to get predictions
def get_preds(model, test_ds):
    model.eval()
    with torch.no_grad():
        preds = []
        labels = []
        for batch in torch.utils.data.DataLoader(test_ds, batch_size=16):
            input_ids = batch["input_ids"]
            attention_mask = batch["attention_mask"]
            label_ids = batch["label"]

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            preds.extend(torch.argmax(logits, dim=1).tolist())
            labels.extend(label_ids)
        return labels, preds

# 🧠 Evaluate on UNMASKED test set (same structure)
# external_test_unmasked = external_test_masked  # You can load a separate unmasked version if available

y_true_unmasked, y_pred_unmasked = get_preds(model, external_test_unmasked)
print("📊 Unmasked Model (External Test Set):")
print(f"Accuracy: {accuracy_score(y_true_unmasked, y_pred_unmasked):.4f}")
print(classification_report(y_true_unmasked, y_pred_unmasked, target_names=[id2label[i] for i in sorted(id2label)]))

# 🧠 Evaluate on MASKED (Structure-Aware) test set
y_true_masked, y_pred_masked = get_preds(model, masked_dataset)
print("\n📊 Masked (Structure-Aware) Model (External Test Set):")
print(f"Accuracy: {accuracy_score(y_true_masked, y_pred_masked):.4f}")
print(classification_report(y_true_masked, y_pred_masked, target_names=[id2label[i] for i in sorted(id2label)]))

from google.colab import drive
drive.mount('/content/drive')

!zip -r /content/nli_unmasked_model.zip /content/nli_unmasked_model/

from google.colab import files
files.download("/content/nli_unmasked_model.zip")